services:
  - type: web
    name: qr-code-api
    env: python
    region: oregon  # or frankfurt, singapore, etc.
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
